### PR TITLE
Make package compatible with SimpleSchema and Astronomy 2.0

### PR DESCRIPTION
**Pull request by lukejagodzinski**
Hi @stubailo. We've talked today with @aldeed about SimpleSchema and Astronomy. We've discussed how validation work in SS and A and if the `mdg:validation-error` package fits our needs. We've came to conclusion that it needs one little change. Instead having the `details` property per error it's better to keep errors structure plain and keep fields like `value`, `message` on the same level as `type` and `name`. @aldeed is already using such structure and me too in Astronomy 2.0.

I've also added several improvements that I'm using in Astronomy like:

``` js
if (ValidationError.is(err)) {
}
```

for checking if error is an instance of ValidationError. It's much shorter than:

``` js
if (err && err.error === ValidationError.ERROR_CODE) {
}
```

I've also added possibility to change default error message by overriding static property:

``` js
ValidationError.DEFAULT_MESSAGE = 'Validation error';
```

So it would be nice if you could merge this PR as we want to continue our work having the same code base for validation. Using such an error object will allow Astronomy to work nicely with the `aldeed:autoform` package when validation is performed on the server.

### CODE REVIEW

**Comment by stubailo** [comment]
Do we think this is a breaking change and we need to bump the major version? Does it matter? Do we foresee other changes before simple schema and astronomy come out?

**Comment by lukejagodzinski** [comment]
I see that https://atmospherejs.com/mdg/validation-error is still in beta version (0.4.0) so maybe let's merge it and wait for a couple of weeks until we release new versions of SimpleSchema and Astronomy. For tests we may use this package locally without publishing the newest version to Atmosphere. And if we are ready to release new version you could publish it as 1.0. What do you think? Let's also see what @aldeed will say about that idea.

And as I'm thinking right now about this change. It's not breaking compatibility. Actually it's more lose if it goes about the structure of errors array. So it will be compatible but wouldn't force developers to use details property but it will still be acceptable to use it. What do you think?

**Comment by aldeed** [comment]
This is backwards compatible so I see no problem with just merging and releasing as a minor version bump.

@jagi you can do

``` js
 return err instanceof Meteor.Error && err.error === ValidationError.ERROR_CODE;
```

instead of 

``` js
 return err && err instanceof Meteor.Error && err.error === ValidationError.ERROR_CODE;
```

Because `err instanceof Meteor.Error` will return `false` if `err` is undefined or any falsy value.

The one other change I would still like is to get rid of the `Meteor.Error` dependency, but that would require `ddp-server` package changes I think as well as some agreed-upon convention for how a regular Error can indicate that it wants to be serialized to the client. Any chance of that happening, @stubailo?

**Comment by lukejagodzinski** [comment]
@aldeed right! I will change it.

Yes it would be nice to have a way of serializing error to be sent over DDP. As it's done in EJSON right now. You have to provide some options to make a class serializable for DDP usage. One big advantage of that would be that if we have `ValidationError` throw on the server, we would also get `ValidationError` on the client and not `Meteor.Error` with the `ERROR_CODE` set to `validation-error`. It would be easier to check error type.

**Comment by stubailo** [comment]
@aldeed @jagi would it be good to add you both as contributors to the repo and the Meteor package? Sounds like you would have a lot more experience with this stuff than myself.

**Comment by lukejagodzinski** [comment]
@stubailo yes sure, why not :)

**Comment by stubailo** [comment]
@jagi OK please work together! And please let me know before making any major changes.

**Comment by stubailo** [comment]
```
The maintainers for mdg:validation-error are:
mdg
jagi
aldeed
```

**Comment by aldeed** [comment]
@stubailo thanks! Yeah, maybe @jagi and I can come up with a PR for the ddp packages to support arbitrary serializable and client-safe errors.

**Comment by stubailo** [comment]
Sounds great! And don't forget to update the meteor guide :)

**Pull request merged**
